/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXERCISE1_H_RPCGEN
#define _EXERCISE1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Exercise1 {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
	double r;
};
typedef struct Exercise1 Exercise1;

#define DS_Ex1 0x20011001
#define Ex1_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define inner_product 1
extern  int * inner_product_1(Exercise1 *, CLIENT *);
extern  int * inner_product_1_svc(Exercise1 *, struct svc_req *);
extern int ds_ex1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define inner_product 1
extern  int * inner_product_1();
extern  int * inner_product_1_svc();
extern int ds_ex1_1_freeresult ();
#endif /* K&R C */
#define Ex1_2 2

#if defined(__STDC__) || defined(__cplusplus)
#define mean_value 1
extern  double * mean_value_2(Exercise1 *, CLIENT *);
extern  double * mean_value_2_svc(Exercise1 *, struct svc_req *);
extern int ds_ex1_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mean_value 1
extern  double * mean_value_2();
extern  double * mean_value_2_svc();
extern int ds_ex1_2_freeresult ();
#endif /* K&R C */
#define Ex1_3 3

#if defined(__STDC__) || defined(__cplusplus)
#define product 1
extern  double * product_3(Exercise1 *, CLIENT *);
extern  double * product_3_svc(Exercise1 *, struct svc_req *);
extern int ds_ex1_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define product 1
extern  double * product_3();
extern  double * product_3_svc();
extern int ds_ex1_3_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Exercise1 (XDR *, Exercise1*);

#else /* K&R C */
extern bool_t xdr_Exercise1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXERCISE1_H_RPCGEN */
