/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "exercise1.h"

bool_t
xdr_Exercise1 (XDR *xdrs, Exercise1 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->X.X_val, (u_int *) &objp->X.X_len, objp->n,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len,objp->n,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->r))
		 return FALSE;
	return TRUE;
}
