/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "exercise1.h"
#include <rpc/rpc.h>
#include <stdlib.h>


int *
inner_product_1_svc(Exercise1 *argp, struct svc_req *rqstp)
{
	static int  result;

//-------------------------------------------------------
	printf("function1 called!");
    int i;
    int sum = 0;
    
    argp->X.X_val=(int*)malloc(argp->n * sizeof(int));
    argp->Y.Y_val=(int*)malloc(argp->n * sizeof(int));
    

    for (i = 0; i < argp->n; i++) {
        sum += (argp->X.X_val[i]) * (argp->Y.Y_val[i]);
    }
	result = sum;
	printf("The inner product of the 2 vectors is %d\n", result);
//-------------------------------------------------------

    
	return &result;
}

double *
mean_value_2_svc(Exercise1 *argp, struct svc_req *rqstp)
{
	static double  result[2];

//-------------------------------------------------------
	printf("function2 called!");
        int i;
        int sumX=0;
        int sumY=0;
        
    argp->X.X_val=(int*)malloc(argp->n * sizeof(int));
    argp->Y.Y_val=(int*)malloc(argp->n * sizeof(int));
    
        
        for (i = 0; i < argp->n; i++) {
        sumX += argp->X.X_val[i];
        sumY += argp->Y.Y_val[i];
    }
    
    result[0] =(double) sumX / argp->n;
    result[1] =(double) sumY / argp->n;
    
    printf("The mean value of vector X is:%f",result[0]);
    printf("The mean value of vector Y is:%f",result[1]); 
//-------------------------------------------------------
    
	return result;
}

double *
product_3_svc(Exercise1 *argp, struct svc_req *rqstp)
{
	 static double *result;
     result=(double*)malloc(argp->n*sizeof(double));
//-------------------------------------------------------
    argp->X.X_val=(int*)malloc(argp->n * sizeof(int));
    argp->Y.Y_val=(int*)malloc(argp->n * sizeof(int));
     
	printf("function3 called!");
       int i;
       for (i = 0; i < argp->n; i++) {
        result[i] = (argp->r) * ((argp->X.X_val[i]) + (argp->Y.Y_val[i]));
        }
        
     printf("The result of r*(X+Y) is:");
     for (int i = 0; i < argp->n; i++) {
         printf("%.2lf ",result[i]);
     }
     printf("\n");
//-------------------------------------------------------    

	return result;
}
